### PR TITLE
Initialize

### PR DESCRIPTION
**Pull request by zhaomr13**
Initialize the repo

### CODE REVIEW

**Comment by xshi** [comment]
Hi @zhaomr13 , could you please remove all the files inside .svn directories? 

Thanks!
Xin

**Comment by zhaomr13** [comment]
I deleted svn

**Comment by xshi** [comment]
Could you take a look at : https://github.com/cepc/tracking/pull/1/files, then search .svn, you'll find there are still sub directories. 

Thanks.

**Comment by zhaomr13** [comment]
Every .svn should be deleted now.

**Comment by xshi** [comment]
Thanks a lot! Now the files is 33 :)

**Pull request merged**
